# application.yml

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: yenugubala.hari@gmail.com
    password: 9491408146
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false